### PR TITLE
Keep alive

### PR DESCRIPTION
**Pull request by mikroware**
Option the keep the mysql connection alive by executing a mysql query on a configurable interval. Disabled by default. Can be enabled by setting the interval in seconds in the configuration file (see updated README).

---

I decided to stay with `setTimeout` for now. This is because it guarantees that only after a successful execution, the keeping alive is being continued. If using an interval, there is a risk it keeps building up queries even though they all cannot be executed. This also prevents problems when an user configures it to run every second and for some reason some of the executions take over 1 second. Now it is always in strict order.

If you think that my reasoning is off, let me know and I shall change it.

### CODE REVIEW

**Comment by GHMatti** [comment]
I did not see that issue with `setTimeout`, but yeah it is more robust, I agree with that reasoning.

I think `SELECT 1;` or `SELECT NULL;` might be better as queries.

Also you are using oracles mysql? As I never encountered this when idle at all on mariadb.
Furthermore does mysql timeout the connection or the socket? I assume it is the socket.

**Comment by mikroware** [comment]
I think it is the socket that times out, but I am not entirely sure. I do know in my instance the timeout was 10 seconds, maybe that is a hint on where the problem occurs.

I am not running mariadb on my production servers, but plain mysql `mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper` on Ubuntu 18.

**Comment by GHMatti** [comment]
Then I know how to fix it without the keepAlive queries.

```
set mysql_connection_string "mysql://username:password@host/database?supportBigNumbers=true&multipleStatements=true&connectTimeout=3600000&acquireTimeout=3600000"
```

gonna add some better parser in 3.1 so the other string accepts those too.

this is literally the first time i got proper information over this issue.

**Comment by mikroware** [comment]
But `connectTimeout` only increases the timeout the node mysql library uses to fail an attempted connection. Making this longer will not magically create the connection, but only makes the library wait way longer on a connection while the queries keep stacking up in the queue. Right?

**Comment by GHMatti** [comment]
it is not recommended either way, but I can get me up some dockers and see what is causing the issue and play with that.

Maybe just one initial query is enough, as it seems to be an error upon acquiring a connection. The issue seems to be only on mysql 5.7.x, so I'll actually could just run a `SELECT VERSION();` and force the keep alive then.

**Comment by mikroware** [comment]
I must say that I have had a similar issue with a GTA San Andreas multiplayer server where also all of a sudden the mysql connection stopped. That server is connected to the same database as I mentioned earlier. A keep alive query seems to have fixed it there. Maybe this indeed actually is some kind of mysql problem with inactive network connections.

The annoying part in both situations is that it ends in some kind of frozen situation where it is not able to re-create a working connection.

**Comment by GHMatti** [comment]
I can't seem to replicate the behaviour with the mysql:5 docker image, like I hoped to.

So I guess keepAlive querying work around it is. Most suggestions by the author is that there is some fault in peoples network configuration (which seem to commonly hold true), but it seems only to happen consistently on mysql 5.x.

And I do not trust people to be able to properly configure their networks (after all those support requests).

**Pull request merged**
