### PR TITLE
Fixes the issue with scalar executing. 

### PR DESCRIPTION
**Pull request by mikroware**
The `result` variable in the callback is in most cases a valid empty array, which results tests as `true` in a statement. Thus, need to test array validity and length above 0.

Should fix issues #62 and #63

### CODE REVIEW

**Comment by GHMatti** [comment]
I've used @PichotM version of the fix, I am not sure about the keepAlive issue, how and why it appears.

**Comment by mikroware** [comment]
Yes sorry, those were accidental personal commits. The essential was the extra statement below which might be cleaner then PichotM's solution (which assumes it is an array and simply does a javascript true check on the first element).

```
 && Array.isArray(result) && result.length > 0
```

**Comment by GHMatti** [comment]
Well there are some people having issues with the connection timing out on possibly a pool, so I am not certain in how far it is needed or for which mysql versions it is needed, as I never encountered it. So I have to consider adding this with a setInterval though, instead of repeated setTimeout.

For your argument, well...
It looks cleaner, but I am not certain if it covers all the replies from mysql.js

I could not really work on FiveM for months, and I hope, I can get some test servers running for me later today, so I can test stuff again.

**Comment by mikroware** [comment]
We also seem to have that connection timeout problem. Which actually was the reason why I added the `keepAlive` function in my fork (which was not supposed to end up here) in order to test this. I have not recently heard any problems related to the timeout error from my development team though.

Together with the keep alive I also updated the mysql package to the most recent version. So I am not sure what change might have probably fixed the problem.

I use the mysql package in a nodejs project (also older versions) with its connection pooling. There I have not had any trouble with connection timeouts though.

**Comment by GHMatti** [comment]
2.16 already bled memory on linux, although that was months ago, maybe that changed.

**Comment by GHMatti** [comment]
Would you mind doing a proper pr without compiled code for the next release next weekend with the keepAlive in setInterval?

**Pull request closed without merging**
